# Generated by Django 4.1.4 on 2022-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_kategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
